### ISSUE TITLE
Invalid Vizualization

### ISSUE THREAD

**Issue by dogvile-gr** [ClimberAB/ClimberKPI#10]
### Description

Invalid Vizualization

Imported successfully in server but when I tried to use it in sheet (drag n drop) has the following message
"the visualization was not found on the server: cl-kpi"

sorry the server was 3.0

**Comment by MichaelClimber** [comment]
This could be due to the old version of the server combined with a new version of the extension. Please follow the support template so we get some more info. (That said, we would recommend moving up from version 3.0 to a more current version of Qlik Sense ;-))

Kind regards

Michael

**Comment by dogvile-gr** [comment]
Yes indeed. Thanks for the great qlik extension!
Keep up the good work! :)
