### ISSUE TITLE
Enhancement / Feature Addition

### ISSUE THREAD

**Issue by Ashfaq184** [ClimberAB/ClimberKPI#12]
### Description
First of all, Nice work done.

[Description of the issue]

There is no issue, But I would like you to ask if there is possibility to add sheet navigation feature to this extension. Such that whenever user Qlik on this KPI it will take him to relevent sheet for further analysis.

### Steps to Reproduce

There is no issue, But I would like you to ask if there is possibility to add sheet navigation feature to this extension. Such that whenever user Qlik on this KPI it will take him to relevent sheet for further analysis.

##### Expected behavior

There is no issue, But I would like you to ask if there is possibility to add sheet navigation feature to this extension. Such that whenever user Qlik on this KPI it will take him to relevent sheet for further analysis.

##### Actual behavior

There is no issue, But I would like you to ask if there is possibility to add sheet navigation feature to this extension. Such that whenever user Qlik on this KPI it will take him to relevent sheet for further analysis.

### Environment
```
[June] Desktop
[ ] Enterprise
```
### Versions

* Extension version:
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by Ashfaq184** [comment]
Sorry I missed Hover Option.
It worked like a charm.

**Comment by mickeg** [comment]
Great 👍 :)
