### ISSUE TITLE
All source is minified, no readable source is available

### ISSUE THREAD

**Issue by coderjoe** [ClimberAB/ClimberKPI#15]
### Description

I want to view/audit the source to check its implementation and maybe even add functionality, but no usable source is available.

### Steps to Reproduce

1. Download the repo
2. Try and read the source
3. Despair

##### Expected behavior

For the source to be available unminified somewhere.

##### Actual behavior

I entered a state of deep depression realizing that the source was neigh unreadable.

**Comment by edwardhallgren** [comment]
Hi, we have decided to only have the minified code. You're welcome to add request to for functionality to this project and we will consider it

**Comment by coderjoe** [comment]
Thanks for your candor. I'll suggest my clients avoid use of this extension going forward as there's no way to perform independent code review.

**Comment by MichaelClimber** [comment]
Hi Coderjoe and thank you for your comments. 
The examples released from us on Branch/GitHub are only a small part of our full offering. We do realize that customers want more security and for that reason we offer a subscription where we fully support this (and our other) extensions. Please let us know if that is of interest to your organization.

**Comment by coderjoe** [comment]
Does your full subscription provide unminified code?

**Comment by MichaelClimber** [comment]
Hi again,
not normally no but if that is critical for your company maybe we could work something out. 
Now I am really curious though! What type of company do you represent that would go through the actual code of software you buy?! And did you manage to convince Qlik to give you their source code when you bought Qlik Sense?

**Comment by coderjoe** [comment]
Do you not do at very least a minimal review of 3rd party components you decide to include in your projects? In our case our minimal review of components for open source software includes verifying it's an acceptable license as well as a quick evaluation of 3rd party components that the open source software requires to operate.

Your product/company in my limited experience your product is unique in that it [advertises the extensions as open source](https://www.youtube.com/watch?v=9zdfYshNel4), releases under a very permissive license (MIT as of the time of this post), but does not provide the unmodified source code. Hence my support request.

Don't get me wrong, I'm not trying to say your choice is wrong or bad, it's just your choice.

**Comment by MichaelClimber** [comment]
Ok, I probably misunderstood your comment then. Apologies for that. 
Overall I agree with your assessment of the situation. It is a bit odd of a mix and we should probably change the license model on GitHub too at some point.

**Comment by coderjoe** [comment]
Again I appreciate your open and honest communication. If at some point in the future we need a more comprehensive solution and not just a quick plug-in KPI extension I'll take another look. 

Best wishes!

**Comment by julmot** [comment]
I'd also like to know more about the tool and dig into it – especially because I want to further extend it (like e.g. change the icons). But that's not possible when you're not uploading un-minified code. It makes no sense for me to host the library under the MIT license and not upload the source – don't even know if this is legal (MIT means open source, but this isn't).

**Comment by coderjoe** [comment]
What in the world would make this illegal? Inconvenient for extension maybe, but illegal? That's feels like a pretty ridiculous claim.
