### ISSUE TITLE
Extension does not export as pdf or image

### ISSUE THREAD

**Issue by mrgran** [ClimberAB/ClimberKPI#16]
### Description

When right clicking the visual to export to PDF the visual does not show in the exported file. It returns a blank page.  When right clicking the visual to export as image, an error message is returned 

### Steps to Reproduce

1. assuming kpi visual is created, right click
2. click export
3. export to pdf
4. keep standard settings: paper size A4, resolution 200, orientation landscape, aspect ratio keep current size

##### Expected behavior

the KPI visual exports as it appears in a dashboard

##### Actual behavior

A blank page is returned

### Environment
```
[x ] Desktop April 2018
[x ] Enterprise February 2018
```
### Versions

* Extension version: 1.4.0 on qlik version April 2018, 1.4,1 on April 2018
* Browser: 
* Qlik Sense: April 2018 
* Operating system: 
* [Other relevant versions]

**Comment by edwardhallgren** [comment]
Hi,

Please try the latest version (1.4.3).

Br
Edward

**Comment by edwardhallgren** [comment]
could try to clear the cache in your web browser?

**Comment by mrgran** [comment]
So exporting works on your end?  I've never gotten it to export.  I cleared my cache but same result: a blank pdf and error message when exporting as image

**Comment by edwardhallgren** [comment]
Hi again, We find an error for april 2018. Try the new version 1.4.4

Br
Edward

**Comment by mrgran** [comment]
Works now.  Thanks for the update!
