### ISSUE TITLE
Arrows not working in Single Configurator

### ISSUE THREAD

**Issue by BerndPodhradsky** [ClimberAB/ClimberKPI#18]
### Description

When using Climber KPI 1.4.5 in single configurator, fonts are not properly loaded and displayed (e.g. there's a read square instead of an arrow). I am aware of (probably) similar problems when using ClimberKPI in a mashup, but of course the fix there won't help in my case. Trying to replace the relative paths with full paths in climber's original CSS file does not work, the HTTP 404 errors below still appear.

### Steps to Reproduce

1. Open Object in Single Configurator
2. See for yourself :)

##### Expected behavior

I expected to see the arrows.

##### Actual behavior

The arrows are rectangles in the correct color.

### Environment

[X ] Desktop (April 2018)
[X] Enterprise (April 2018)

### Versions

* Extension version: 1.4.5
* Browser:  Chrome (latest)
* Qlik Sense:  April 2018
* Operating system: Win10

### Screenshots
No screenshot, but the google chrome console says that there was an HTTP 404 error when trying to get a resource from "host/cl-kpi/lib/fonts/...." which is pretty strange, because it should be "host/extensions/cl-kpi/lib/fonts/..." shouldn't it?

**Comment by Lojdquist** [comment]
Hi,

We changed the structure for how the KPI extension is built in v1.5.0. Try upgrading to the latest version and let us know if the problem remains.

**Comment by edwardhallgren** [comment]
reopen if problem still occurs in latest version
