### ISSUE TITLE
Option to select the target percentage type

### ISSUE THREAD

**Issue by davidth85** [ClimberAB/ClimberKPI#19]
### Description

I would like to be able to choose between a growth percentage or coverage percentage versus the target

### Steps to Reproduce

It's an idea. not an issue

##### Expected behavior

Option to customize the target percentage shown in the KPI

##### Actual behavior

Target percentage always shows growth, which is great when you compare something in different time periods, but it's not very meaningful when you try to see something like sales against budget, where a direct percentage would be the way to go, i.e., A/B instead of (A/B)-1.

### Environment
```
[ ] Desktop
[ ] Enterprise
```
### Versions

* Extension version:
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by MichaelClimber** [comment]
Thank you for your feedback! All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.
