### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by Gonsty** [ClimberAB/ClimberKPI#2]
### Description

The extension does not allow for exporting as an image or pdf. Also when exporting a whole sheet or a story containing a snapshot of the extension, the area where the extension lies shows blank. Please enable exporting. We love this extension but need to be able to export it. Thank you.

http://help.qlik.com/en-US/sense-developer/June2017/Subsystems/Extensions/Content/Howtos/extensions-enable-export.htm

##### Expected behavior

We expect to have options to export to image and pdf. Also we expect it to show up in whole sheet exports and story exports.

##### Actual behavior

There are no image or pdf export options. KPI doesn't show up in whole sheet or story exports.

### Environment
```
[ ] Desktop
[X] Enterprise
```
### Versions

* Extension version: 1.1.0
* Browser: Chrome
* Qlik Sense: June 2017
* Operating system: Windows Server 2016, virtual
* [Other relevant versions]

**Comment by edwardhallgren** [comment]
We are aware of this problem and working on a solution

**Comment by SEOmar** [comment]
I think it's related but I'm trying to export the error links from the Chrome browser extension but nothing happens.

**Comment by edwardhallgren** [comment]
Export is now working in v 1.2.0

**Comment by Gonsty** [comment]
Thank you so much! This is awesome.
