### ISSUE TITLE
Support custom abbreviations

### ISSUE THREAD

**Issue by gmen85** [ClimberAB/ClimberKPI#21]
From v. April 18, QS has the capability of custom abbreviations eg 2.2k instead of 2200 and 4.5M instead of 4500000.  ATM, I can use this with the default KPI object, but not with yours. Will this be implemented?

**Comment by Lojdquist** [comment]
Hi,

Which version of the KPI extension are you currently using? You can find this information by editing the extension and looking in the about panel to the left.

**Comment by Lojdquist** [comment]
Custom abbreviations are supported in the way you have explained, reopen the issue if we have misunderstood your explanation. Br Axel.
