### ISSUE TITLE
Visualization Not Found on server:KPI

### ISSUE THREAD

**Issue by mohit-llp** [ClimberAB/ClimberKPI#23]
I have a problem of visualization of KPI in "April version of Qlik Sense".
Also, I could import the updated extension on the QMC. But it showed the same error.

### Versions

* Extension version: 1.4.1
* Browser:   Google Chrome
* Qlik Sense: April 2018
* Operating system: Windows 10

 Screenshots:

![capture](https://user-images.githubusercontent.com/44094302/46882297-c06d2100-ce6b-11e8-9dca-b69fbbdf3292.PNG)

![kpi_problem](https://user-images.githubusercontent.com/44094302/46882309-cbc04c80-ce6b-11e8-84e0-20987a6134c9.PNG)

**Comment by MichaelClimber** [comment]
SimpleKPI that you get error messages for is not our extension. We have the Climber KPI. It's probably this one you have: https://github.com/alner/qsSimpleKPI
