### ISSUE TITLE
Cannot read property 'showIconWithTitle' of null

### ISSUE THREAD

**Issue by ArchFolken** [ClimberAB/ClimberKPI#24]
### Description

Hi,

When I'm using this awesome extension, I have the following error in the console : 

require.js?1522774745642:1 TypeError: Cannot read property 'showIconWithTitle' of null
    at p.M.showIconWithTitle (cl-kpi.js?1522774745642:1)
    at fn (eval at compile (require.js?1522774745642:1), <anonymous>:4:271)
    at p.$digest (require.js?1522774745642:1)
    at client.js?1522774745642:1
    at require.js?1522774745642:1
    at o (require.js?1522774745642:1)
    at require.js?1522774745642:1
(anonymous) @ require.js?1522774745642:1

### Steps to Reproduce

1. Create a Kpi component
2. Navigate between pages of the Qlik Application
3. Open the console.

##### Expected behavior

No error in the console log

##### Actual behavior

require.js?1522774745642:1 TypeError: Cannot read property 'showIconWithTitle' of null
    at p.M.showIconWithTitle (cl-kpi.js?1522774745642:1)
    at fn (eval at compile (require.js?1522774745642:1), <anonymous>:4:271)
    at p.$digest (require.js?1522774745642:1)
    at client.js?1522774745642:1
    at require.js?1522774745642:1
    at o (require.js?1522774745642:1)
    at require.js?1522774745642:1
(anonymous) @ require.js?1522774745642:1

### Environment
```
[ ] Desktop
[x] Enterprise
```
### Versions

* Extension version:
* Browser: Chrome
* Qlik Sense: June 2018
* Operating system: Windows 10
* [Other relevant versions]

**Comment by edwardhallgren** [comment]
Hi, what version of the extension do you have. Please update to the latest version. Br Edward

**Comment by edwardhallgren** [comment]
Please reopen if problem still occurs. Br Edward
