### ISSUE TITLE
September release 

### ISSUE THREAD

**Issue by jojonsson** [ClimberAB/ClimberKPI#25]
### Description

Is this extension tested with sense september release.I get an error saying cl-kpi is not avaliable when i try to use it in a application after upgrade.

![image](https://user-images.githubusercontent.com/44234014/47091971-40a5d480-d226-11e8-8f7f-d7a0898d3cf0.png)

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

### Environment
```
[ ] Desktop
[ ] Enterprise
```
### Versions

* Extension version:
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by edwardhallgren** [comment]
Hi, what version of the extension do you have? Br Edward

**Comment by edwardhallgren** [comment]
Hi, can you tro to clear cache in your web browser
https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by jojonsson** [comment]
I have cleared the cache (all time) in chrome and restarted the browser but get same error.
I tried with edge also and get this error
![image](https://user-images.githubusercontent.com/44234014/47790534-b70f0000-dd17-11e8-9b8e-05702a687a19.png)

**Comment by edwardhallgren** [comment]
So the KPI extension is invalid, or is it just this message? The error message seems to have with a theme file.

**Comment by jojonsson** [comment]
I downloaded the latest version 1.5.2 and then it started to work so i guess something have been done.
Thanks.
