### ISSUE TITLE
Background Image not visible in Offline mode

### ISSUE THREAD

**Issue by thomaslammens82** [ClimberAB/ClimberKPI#26]
### Versions
* Extension version: 1.5.2
* Qlik Sense: 12.26.3
* Browser:  iPad APP - 1.5.1.17 (and others)

### Description
When using the KPI extension on the iPad app in online mode the KPI box is showing the background image. When I download the app the image is not shown and I get a white background.

### Console errors
None

### Steps to Reproduce
1. Create an KPI box with background image from a content library
2. Download the app in QS Mobile 
2. Open the sheet with the KPI box

##### Expected behavior
The background image is shown just like it shows in online mode.

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions where this should be solved.
