### ISSUE TITLE
Code not visible

### ISSUE THREAD

**Issue by mrgran** [ClimberAB/ClimberKPI#28]
### Are you using the latest version 1.5.1 of the Climber KPI? If no, upgrade and see if the issue is fixed.
Yes currently on 1.5.2

### Versions
* Extension version: 1.5.2
* Qlik Sense: September 2018
* Browser:  Chrome

*Extension version can be found under About in the property panel of the extension in Edit-mode or in the Qlik Sense Dev-hub.*  

### Description
Cannot see code.  Appears encoded

### Steps to Reproduce

1. Open the scripts and cannot edit code

##### Expected behavior

To see the code:

![climbercode](https://user-images.githubusercontent.com/20053364/51132379-b3a7f280-17f7-11e9-9795-da55a5a9d19a.PNG)

**Comment by MichaelClimber** [comment]
The code is not available for change (as is also stated in the licence).

**Comment by MichaelClimber** [comment]
We minified the code a long time ago since we had no additions from the outside anyway. Now it is also a way of protecting our code that we put a lot of time and money into.
