### ISSUE TITLE
Actual value not displaying when 'Comparison Focus' text layout is selected

### ISSUE THREAD

**Issue by rachital** [ClimberAB/ClimberKPI#29]
Versions
* Extension version: 1.6.1
* Qlik Sense: November 2018 Patch 2
* Browser:  Chrome, IE

### Description
Extension does not display Actual value when you chose 'Comparison focus' under Text Layout , see below.
![image](https://user-images.githubusercontent.com/47607109/52807549-c2353400-3059-11e9-84e1-490aa3889568.png)

Using KPI focus:
![image](https://user-images.githubusercontent.com/47607109/52807583-e1cc5c80-3059-11e9-9451-a57b414e52f3.png)

We recently upgraded our test environment for Qlik Sense to November 2018 Patch 2 and installed the latest version of the extension. 

##### Expected behavior
This is how the extension currently displays data in our production env which is on Qlik Sense version April 2018.
![image](https://user-images.githubusercontent.com/47607109/52807899-b39b4c80-305a-11e9-842a-fbabdaf4b231.png)

The same view is expected with Qlik Sense version November 2018 Patch 2.

**Comment by GrahamRothwell** [comment]
Same problem with 1.6.2

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.
