### ISSUE TITLE
Icon of extension not showing in a mashup of qliksense

### ISSUE THREAD

**Issue by soumik14** [ClimberAB/ClimberKPI#3]
### Description

[Description of the issue]
When creating a mashup, use this extension with an icon of your choice. When you place the extension in the placeholder of your html page the icon does not appear. It shows an error in the html page also. Attached the screenshots for reference. 

### Steps to Reproduce

1. Create the ClimberKPI extension in your app with two measures and place an icon.
2. Go to dev-hub and start creating your mashup with the app you just created.
3. In the html page of your mashup, create a placeholder so that you can place the extension ClimberKPI. Notice that you will see that the icon is not displaying properly while the numbers on the side are perfectly displayed. 
4. Press F12 on the browser, notice the errors. Pasted screenshots of the error.

##### Expected behavior

The icon should be displayed in the mashup as it is showing in the app which we created.

##### Actual behavior

[What actually happened]

[ ] Enterprise
```
### Versions

* Extension version:
* Browser: Chrome, Mozilla
* Qlik Sense: 3.2
* Operating system: 
* [Other relevant versions]

### Screenshots
![climberkpi_issue1](https://user-images.githubusercontent.com/13237078/29128029-5052647a-7d40-11e7-929d-288771f2417b.JPG)
![climberkpi_issue2](https://user-images.githubusercontent.com/13237078/29128051-5ededcc6-7d40-11e7-8492-ed7e278e755e.JPG)

**Comment by mickeg** [comment]
Hi, sorry for late response.

This is a known issue which we are working on, I will let you know once it's fixed!
//Mikael

**Comment by mickeg** [comment]
I have a fix for this now:

- Browse to the folder C:\Users\username\Documents\Qlik\Sense\Extensions\cl-kpi\lib\fonts. 
- Copy the files climbericons.eot, climbericons.svg, climbericons.ttf, climbericons.woff
- Paste the files into your mashup extension folder. C:\Users\username\Documents\Qlik\Sense\Extensions\MashupName
- In the mashup editor, add this code to the css file:

```
@font-face {
    font-family: 'climbericons';
    src: url('climbericons.eot?slo2rd');
    src: url('climbericons.eot?slo2rd#iefix') format('embedded-opentype'), url('climbericons.ttf?slo2rd') format('truetype'), url('climbericons.woff?slo2rd') format('woff'), url('climbericons.svg?slo2rd#climbericons') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Of course you can change the path where you put the files and then change the src in the css file. 
Let me know if you have any trouble getting this to work :) 

//Mikael
