### ISSUE TITLE
ClimberKPI overrides console.log

### ISSUE THREAD

**Issue by pschiffmann** [ClimberAB/ClimberKPI#30]
ClimberKPI 1.6.1 overrides the native functions `console.log`, `console.error`, `console.debug` and `console.warn` with NOP functions, effectively disabling console output for the whole app or mashup.

To reproduce, open an app or mashup with a ClimberKPI object, open the dev tools of your browser, and write: `console.log`. The result I see is: `f (){}`. Unsurprisingly, `console.log("I should see a log output")` doesn't write anything to the console.

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.
