### ISSUE TITLE
Feature request: Hover & Click to open URL

### ISSUE THREAD

**Issue by raqraq** [ClimberAB/ClimberKPI#31]
Hi,
I would like to open an URL (other Qlik App) when hovering over the object.
Love the extention.

**Comment by MichaelClimber** [comment]
Thank you for your feedback! The feature you are asking for is available in the Vizlib KPI designer if you are still interested.

All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.
