### ISSUE TITLE
Visualization Not Found on server

### ISSUE THREAD

**Issue by duckaccount** [ClimberAB/ClimberKPI#4]
### Description

I could import the extension on the QMC.  After developing some reports using this extension on the QlikSense Desktop, I tried to publish them on the QMC. 
However, it showed a Invalid Visualization Error. I can see the reports on the QlikSense Desktop but not after publishing them on the server

Here are the screenshots
![extension](https://user-images.githubusercontent.com/30924815/29208670-a851f5b4-7ea8-11e7-8d06-1474a46f8a4f.PNG)
![qs desktop](https://user-images.githubusercontent.com/30924815/29208676-ae881e18-7ea8-11e7-921d-4dfa9415a0e1.PNG)
![qmc](https://user-images.githubusercontent.com/30924815/29208678-b2128b7c-7ea8-11e7-9efb-07ad79fc1e2b.PNG)

**Comment by soumik14** [comment]
Hi,

I am using this visualization in my project, works fine on my qliksense server. However, i have heard that some visualizations are generating an error on the newest july version of the server.

**Comment by duckaccount** [comment]
Hi,
My version of the server is 2.1.1.0 Can you tell me which files have you removed from the zip file before importing it to the server?

**Comment by edwardhallgren** [comment]
Hi,

Have you the latest version of the extension 1.1.1. Could you press f12 then console and post the message. You also have an old version om QS and it could be a idea to update.

**Comment by duckaccount** [comment]
Here..

![console](https://user-images.githubusercontent.com/30924815/29400262-46392900-834a-11e7-97ca-eab71cbde23c.PNG)

**Comment by edwardhallgren** [comment]
This is related to your Qlik Version, our extension is compatible from Qlik Sense >3.0. We recommend you to update your server version to a later version.
