### ISSUE TITLE
No space between Measure name (of target) and measure when using targets with KPI Focus

### ISSUE THREAD

**Issue by MGGSIDA** [ClimberAB/ClimberKPI#6]
### Description

There is no space between the target measure name and the measure using Text Layout: KPI Focus
This does not happen for other Text Layouts

### Steps to Reproduce
Select two measures, target mode and Text Layout: KPI Focus
![grafik](https://user-images.githubusercontent.com/23421993/30111330-8471770e-930d-11e7-8e4a-2916ff339244.png)

Expected behavior

At least one character space

Actual behavior
no space

Environment

[x] Enterprise June 2017 SR2

Versions

    Extension version: 1.2.0
    Browser: Firefox 52.3.0
    Qlik Sense: June 2017 SR2
    Operating system: Windows 7
    [Other relevant versions]

### Screenshots
![grafik](https://user-images.githubusercontent.com/23421993/30111410-c9a217ca-930d-11e7-8852-58842e233867.png)

**Comment by mickeg** [comment]
@MGGSIDA I released 1.2.2 which fixes this issue. Thank you for letting us know.

//Mikael
