### ISSUE TITLE
Enhancement: Additional Label for Comparison Focus

### ISSUE THREAD

**Issue by dggauthier** [ClimberAB/ClimberKPI#7]
## Description

Not really an Issue, more of an enhancement. I was wondering if it would be possible to have an additional label when using the "comparison focus". For the screenshot attached, the design I'm looking for is KPI label on the top (e.g. 'Average Number of Days'), then the first scenario would read 'Current Year', and the target label would read 'Prior Year'.  

## Screenshot 
![image](https://user-images.githubusercontent.com/19920595/30124605-ade50664-9303-11e7-9dc3-c17902f531c4.png)

**Comment by mickeg** [comment]
Hi, thanks for the suggestion! We will look into it but I can't promise it will be implemented. Keep an eye on the change log in upcoming releases. :) 

//Mikael
