### ISSUE TITLE
icon not shown using Extension in a mashup

### ISSUE THREAD

**Issue by shofmannka** [ClimberAB/ClimberKPI#8]
### Description
If a use the Extension in a mashup the icons are not shown.

The error seems to come because the extension sub-folder is doubled:
http://<SERVER>/**extensions/extensions**/cl-kpi/lib/fonts/climbericons.ttf?slo2rd
[Description of the issue]

### Steps to Reproduce

1. [Step one]
Install Extension in Qlik Server
2. [Step two]
Go to Dev-hub and select mashup editor.
3. ...
Create a new mashup with standard template. 
Select an app with objects using ClimberKPI Extension.
Drag&Drop this object on the mashup template page.
Make a preview of new mashup. The Icons are not shown.

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

### Environment
```
[ ] Desktop
[ ] Enterprise
```
### Versions

* Extension version:
1.2.2
* Browser: 
Chrome
* Qlik Sense: 
Qlik Sense Server June Edition Path 1
* Operating system: 
Windows 7
* [Other relevant versions]

**Comment by mickeg** [comment]
Hi! This is a known issue (https://github.com/ClimberAB/ClimberKPI/issues/3) and we have a fix for this.

- Browse to the folder C:\Users\username\Documents\Qlik\Sense\Extensions\cl-kpi\lib\fonts. 
- Copy the files climbericons.eot, climbericons.svg, climbericons.ttf, climbericons.woff
- Paste the files into your mashup extension folder. C:\Users\username\Documents\Qlik\Sense\Extensions\MashupName
- In the mashup editor, add this code to the css file:

```
@font-face {
    font-family: 'climbericons';
    src: url('climbericons.eot?slo2rd');
    src: url('climbericons.eot?slo2rd#iefix') format('embedded-opentype'), url('climbericons.ttf?slo2rd') format('truetype'), url('climbericons.woff?slo2rd') format('woff'), url('climbericons.svg?slo2rd#climbericons') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Let me know if you have any trouble getting this to work :) 
//Mikael
