### ISSUE TITLE
Work with single measure

### ISSUE THREAD

**Issue by igorrobertifoc** [ClimberAB/ClimberKPI#9]
Hello, 
congratulation for the usefull Widget, I would like to advice a new feature : 
can be very usefull to work with a single measure insead of a second target measure.

Example: 
TREND                    MEASURE
01.01.2017              5
02.01.2017              3
03.01.2017              7
04.01.2017              8
05.01.2017              7

The KPI can show the last value ( 7 ) and compared with the precedent value (8), in this case the difference is -1.

The chart can show values 5,3,7,8,7 compared to the day before value (UNKNOW,5,3,7,8).

I hope I wrote correctly my view.

Regards

**Comment by MichaelClimber** [comment]
Hi,
you can achieve this by using set-analysis and a third measure but it is a bit of a hack to be honest. We recognize the need for a better approach and will discuss how to best implement that without sacrificing the simplicity of the extension too much. Feel free to let us know your thoughts on how to implement.

**Comment by igorrobertifoc** [comment]
Thank you very much for your reply. To be honest, an hack is enought for me.
But if you would like to improve the extensionthe easy way to configure can be:
- Add measure
- Add trend
- No target (second measure), 

This can show the chart based on trend dimension and measure, (target measure can be recalculated by shifting the main measure).

What do you think?

Thank you very much

Igor

**Comment by MichaelClimber** [comment]
Sounds like reasonable requests. We will consider them for future releases.

Kind regards

Michael
